#ifndef NAMED_LIST_STRUCT_LOGICVAR_H
#define NAMED_LIST_STRUCT_LOGICVAR_H

#include "logic/logicvar.h"

class NAMED_LIST_STRUCT_LOGICVAR {
public:
	STRING m_name;  // 0x00
	LOGICVAR m_var; // 0x04

	~NAMED_LIST_STRUCT_LOGICVAR();
	NAMED_LIST_STRUCT_LOGICVAR();
	NAMED_LIST_STRUCT_LOGICVAR& operator=(const NAMED_LIST_STRUCT_LOGICVAR& p_other);
};

#endif
