cmake_minimum_required(VERSION 3.22)

if(NOT WORK_DIR)
    message(FATAL_ERROR "WORK_DIR is required")
endif()
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Pinned shader-tool bootstrap requires a Linux x64 host; normal game builds use embedded shaders")
endif()
execute_process(COMMAND uname -m OUTPUT_VARIABLE architecture OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT architecture STREQUAL "x86_64")
    message(FATAL_ERROR "Pinned shader-tool bootstrap requires a Linux x64 host")
endif()
find_program(GIT_EXECUTABLE git REQUIRED)
set(revision "1ff05bec573988a98ef9e0260b4da44f512b8367")
set(source "${WORK_DIR}/shadercross")
set(prefix "${WORK_DIR}/prefix")

function(run)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${WORK_DIR}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Shader tool command failed: ${ARGV}")
    endif()
endfunction()

file(MAKE_DIRECTORY "${WORK_DIR}")
if(NOT EXISTS "${source}")
    run("${GIT_EXECUTABLE}" clone --filter=blob:none --no-checkout
        https://github.com/libsdl-org/SDL_shadercross.git "${source}")
    run("${GIT_EXECUTABLE}" -C "${source}" checkout "${revision}")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" rev-parse HEAD
    OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT actual STREQUAL revision)
    message(FATAL_ERROR "Shader tools must use ${revision}")
endif()
file(READ "${source}/src/SDL_shadercross.c" compiler)
set(original "    Uint32 argCount = 0;")
set(strict "    Uint32 argCount = 0;\n    args[argCount++] = (LPCWSTR)L\"-Gis\";")
string(FIND "${compiler}" "${strict}" strict_position)
if(strict_position EQUAL -1)
    string(FIND "${compiler}" "${original}" original_position)
    if(original_position EQUAL -1)
        message(FATAL_ERROR "Pinned shader compiler argument builder changed")
    endif()
    string(REPLACE "${original}" "${strict}" compiler "${compiler}")
    file(WRITE "${source}/src/SDL_shadercross.c" "${compiler}")
endif()
run("${GIT_EXECUTABLE}" -C "${source}" submodule update --init external/SPIRV-Cross)
run("${CMAKE_COMMAND}" -DCMAKE_SYSTEM_NAME=Linux
    -P "${source}/build-scripts/download-prebuilt-DirectXShaderCompiler.cmake")
run("${CMAKE_COMMAND}" -S "${source}/external/SPIRV-Cross" -B "${WORK_DIR}/spirv-cross" -G Ninja
    -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=${prefix}"
    -DSPIRV_CROSS_SHARED=ON -DSPIRV_CROSS_CLI=OFF -DSPIRV_CROSS_ENABLE_TESTS=OFF)
run("${CMAKE_COMMAND}" --build "${WORK_DIR}/spirv-cross" --parallel 4)
run("${CMAKE_COMMAND}" --install "${WORK_DIR}/spirv-cross")
if(SDL_PREFIX)
    set(ENV{CMAKE_PREFIX_PATH} "${SDL_PREFIX}:$ENV{CMAKE_PREFIX_PATH}")
endif()
run("${CMAKE_COMMAND}" -S "${source}" -B "${WORK_DIR}/build" -G Ninja
    -DCMAKE_BUILD_TYPE=Release "-DCMAKE_PREFIX_PATH=${prefix}"
    -DSDLSHADERCROSS_SHARED=OFF -DSDLSHADERCROSS_STATIC=ON -DSDLSHADERCROSS_CLI=ON
    -DSDLSHADERCROSS_TESTS=OFF -DSDLSHADERCROSS_INSTALL=OFF -DSDLSHADERCROSS_VENDORED=OFF)
run("${CMAKE_COMMAND}" --build "${WORK_DIR}/build" --parallel 4)
message(STATUS "ALIEN_SHADERCROSS=${WORK_DIR}/build/shadercross")
