include_guard(GLOBAL)

function(ffmpeg_runtime_lines text result)
    string(REPLACE "\r\n" "\n" lines "${text}")
    string(REPLACE "\n" ";" lines "${lines}")
    set("${result}" "${lines}" PARENT_SCOPE)
endfunction()

function(ffmpeg_runtime_require_families families binary)
    set(expected avcodec avformat avutil swresample swscale)
    set(reached "${families}")
    list(REMOVE_DUPLICATES reached)
    list(SORT reached)
    if(NOT "${reached}" STREQUAL "${expected}")
        message(FATAL_ERROR "Executable does not load all five FFmpeg libraries: ${binary}: ${reached}")
    endif()
endfunction()

function(ffmpeg_check_architecture binary platform arch)
    if(NOT EXISTS "${binary}" OR IS_DIRECTORY "${binary}")
        message(FATAL_ERROR "Binary is missing: ${binary}")
    endif()
    if(NOT arch MATCHES "^(x86|x64|arm64)$")
        message(FATAL_ERROR "Unsupported target architecture: ${arch}")
    endif()
    if(platform STREQUAL "macos")
        if(arch STREQUAL "x64")
            set(expected x86_64)
        elseif(arch STREQUAL "arm64")
            set(expected arm64)
        else()
            message(FATAL_ERROR "Unsupported macOS architecture: ${arch}")
        endif()
        ffmpeg_command(arches lipo -archs "${binary}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" arches "${arches}")
        if(NOT expected IN_LIST arches)
            message(FATAL_ERROR "Wrong Mach-O architecture: ${binary}: ${arches}, wanted ${arch}")
        endif()
        return()
    endif()
    file(SIZE "${binary}" size)
    if(size LESS 64)
        message(FATAL_ERROR "Truncated executable header: ${binary}")
    endif()
    file(READ "${binary}" header LIMIT 64 HEX)
    if(platform STREQUAL "windows")
        if(NOT header MATCHES "^4d5a")
            message(FATAL_ERROR "Not a PE binary: ${binary}")
        endif()
        set(offset_hex "")
        foreach(index 126 124 122 120)
            string(SUBSTRING "${header}" ${index} 2 byte)
            string(APPEND offset_hex "${byte}")
        endforeach()
        math(EXPR offset "0x${offset_hex}")
        math(EXPR end "${offset} + 6")
        if(offset LESS 64 OR offset GREATER 1048576 OR end GREATER size)
            message(FATAL_ERROR "Invalid PE header offset: ${binary}")
        endif()
        file(READ "${binary}" pe OFFSET ${offset} LIMIT 6 HEX)
        if(arch STREQUAL "x86")
            set(expected "504500004c01")
        elseif(arch STREQUAL "x64")
            set(expected "504500006486")
        else()
            set(expected "5045000064aa")
        endif()
        if(NOT pe STREQUAL expected)
            message(FATAL_ERROR "Wrong PE signature/machine: ${binary}: ${pe}, wanted ${arch}")
        endif()
    elseif(platform STREQUAL "linux")
        if(arch STREQUAL "x86")
            set(expected_class "7f454c460101")
            set(expected_machine "0300")
        elseif(arch STREQUAL "x64")
            set(expected_class "7f454c460201")
            set(expected_machine "3e00")
        else()
            set(expected_class "7f454c460201")
            set(expected_machine "b700")
        endif()
        string(SUBSTRING "${header}" 0 12 elf_class)
        string(SUBSTRING "${header}" 36 4 machine)
        if(NOT elf_class STREQUAL expected_class OR NOT machine STREQUAL expected_machine)
            message(FATAL_ERROR "Wrong ELF signature/class/machine: ${binary}, wanted little-endian ${arch}")
        endif()
    else()
        message(FATAL_ERROR "Unsupported package platform: ${platform}")
    endif()
endfunction()

function(ffmpeg_runtime_real_binaries executable candidates root result)
    set(binaries "${executable}" ${candidates})
    set(resolved "")
    foreach(path IN LISTS binaries)
        ffmpeg_inside("${path}" "${root}" contained)
        if(NOT contained OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
            message(FATAL_ERROR "Missing or escaping package binary: ${path}")
        endif()
        file(REAL_PATH "${path}" real)
        list(APPEND resolved "${real}")
    endforeach()
    list(REMOVE_DUPLICATES resolved)
    list(SORT resolved)
    set("${result}" "${resolved}" PARENT_SCOPE)
endfunction()

function(ffmpeg_runtime_linux executable package_dir library_dir arch)
    get_filename_component(executable_dir "${executable}" DIRECTORY)
    if(NOT executable_dir STREQUAL library_dir)
        message(FATAL_ERROR "Linux release libraries must be adjacent to OpenGromada")
    endif()
    file(GLOB candidates LIST_DIRECTORIES FALSE "${library_dir}/*.so*")
    ffmpeg_runtime_real_binaries("${executable}" "${candidates}" "${package_dir}" binaries)
    file(REAL_PATH "${executable}" main_binary)
    foreach(binary IN LISTS binaries)
        ffmpeg_check_architecture("${binary}" linux "${arch}")
        ffmpeg_command(ignored patchelf --set-rpath "$ORIGIN" "${binary}")
        ffmpeg_command(rpath patchelf --print-rpath "${binary}")
        string(STRIP "${rpath}" rpath)
        if(NOT rpath STREQUAL "$ORIGIN")
            message(FATAL_ERROR "Failed to make RPATH relocatable: ${binary}")
        endif()
        ffmpeg_command(needed patchelf --print-needed "${binary}")
        ffmpeg_runtime_lines("${needed}" names)
        foreach(name IN LISTS names)
            if(name MATCHES "/")
                message(FATAL_ERROR "Non-relocatable ELF dependency in ${binary}: ${name}")
            endif()
        endforeach()
    endforeach()
    foreach(binary IN LISTS binaries)
        ffmpeg_command(dependencies ldd "${binary}")
        if(dependencies MATCHES "not found")
            message(FATAL_ERROR "Unresolved dependency in ${binary}:\n${dependencies}")
        endif()
        ffmpeg_runtime_lines("${dependencies}" lines)
        set(reached "")
        foreach(line IN LISTS lines)
            if(line MATCHES "^[ \t]*([^ \t]+)[ \t]+=>[ \t]+(/.+)[ \t]+\\(0x[0-9a-fA-F]+\\)")
                set(name "${CMAKE_MATCH_1}")
                set(resolved "${CMAKE_MATCH_2}")
                string(STRIP "${resolved}" resolved)
                ffmpeg_inside("${resolved}" "${library_dir}" contained)
                ffmpeg_family("${name}" linux family)
                if(family)
                    list(APPEND reached "${family}")
                    if(NOT contained)
                        message(FATAL_ERROR "FFmpeg resolves outside package: ${name} -> ${resolved}")
                    endif()
                elseif(NOT contained)
                    set(system FALSE)
                    foreach(directory /lib /lib64 /usr/lib /usr/lib64)
                        ffmpeg_inside("${resolved}" "${directory}" in_system)
                        if(in_system)
                            set(system TRUE)
                        endif()
                    endforeach()
                    if(NOT system)
                        message(FATAL_ERROR "Unbundled non-system dependency: ${name} -> ${resolved}")
                    endif()
                endif()
            endif()
        endforeach()
        if(binary STREQUAL main_binary)
            ffmpeg_runtime_require_families("${reached}" "${binary}")
        endif()
    endforeach()
endfunction()

function(ffmpeg_runtime_mac_dependencies binary result)
    ffmpeg_command(output otool -L "${binary}")
    ffmpeg_runtime_lines("${output}" lines)
    set(dependencies "")
    foreach(line IN LISTS lines)
        string(FIND "${line}" " (compatibility version " position)
        if(NOT position LESS 0)
            string(SUBSTRING "${line}" 0 ${position} dependency)
            string(STRIP "${dependency}" dependency)
            list(APPEND dependencies "${dependency}")
        endif()
    endforeach()
    set("${result}" "${dependencies}" PARENT_SCOPE)
endfunction()

function(ffmpeg_runtime_mac_rpaths binary result)
    ffmpeg_command(output otool -l "${binary}")
    ffmpeg_runtime_lines("${output}" lines)
    set(paths "")
    set(in_rpath FALSE)
    foreach(line IN LISTS lines)
        string(STRIP "${line}" line)
        if(line STREQUAL "cmd LC_RPATH")
            set(in_rpath TRUE)
        elseif(line MATCHES "^cmd ")
            set(in_rpath FALSE)
        elseif(in_rpath AND line MATCHES "^path (.+) \\(offset [0-9]+\\)$")
            list(APPEND paths "${CMAKE_MATCH_1}")
            set(in_rpath FALSE)
        endif()
    endforeach()
    list(REMOVE_DUPLICATES paths)
    set("${result}" "${paths}" PARENT_SCOPE)
endfunction()

function(ffmpeg_runtime_macos executable package_dir library_dir arch)
    get_filename_component(executable_dir "${executable}" DIRECTORY)
    get_filename_component(contents "${executable_dir}" DIRECTORY)
    get_filename_component(app "${contents}" DIRECTORY)
    if(NOT app MATCHES "\\.app$" OR NOT executable_dir STREQUAL "${app}/Contents/MacOS"
       OR NOT library_dir STREQUAL "${app}/Contents/Frameworks")
        message(FATAL_ERROR "Expected executable in .app/Contents/MacOS and libraries in Contents/Frameworks")
    endif()
    file(GLOB_RECURSE candidates LIST_DIRECTORIES FALSE "${app}/*.dylib")
    ffmpeg_runtime_real_binaries("${executable}" "${candidates}" "${app}" binaries)
    file(REAL_PATH "${executable}" main_binary)
    foreach(path IN LISTS candidates)
        get_filename_component(name "${path}" NAME)
        string(SHA256 key "${name}")
        file(REAL_PATH "${path}" real)
        if(DEFINED local_real_${key} AND NOT "${local_real_${key}}" STREQUAL "${real}")
            message(FATAL_ERROR "Ambiguous app dependency basename: ${name}")
        endif()
        set(local_${key} "${path}")
        set(local_real_${key} "${real}")
    endforeach()
    foreach(binary IN LISTS binaries)
        ffmpeg_check_architecture("${binary}" macos "${arch}")
        file(CHMOD "${binary}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
        set(options "")
        get_filename_component(name "${binary}" NAME)
        get_filename_component(directory "${binary}" DIRECTORY)
        if(binary MATCHES "\\.dylib$")
            list(APPEND options -id "@rpath/${name}")
        endif()
        ffmpeg_runtime_mac_dependencies("${binary}" dependencies)
        foreach(dependency IN LISTS dependencies)
            get_filename_component(dep_name "${dependency}" NAME)
            string(SHA256 key "${dep_name}")
            if(DEFINED local_${key})
                file(RELATIVE_PATH relative "${directory}" "${local_${key}}")
                list(APPEND options -change "${dependency}" "@loader_path/${relative}")
            elseif(NOT dependency MATCHES "^(/usr/lib/|/System/Library/)")
                message(FATAL_ERROR "Unbundled non-system dependency in ${binary}: ${dependency}")
            endif()
        endforeach()
        ffmpeg_runtime_mac_rpaths("${binary}" rpaths)
        foreach(rpath IN LISTS rpaths)
            list(APPEND options -delete_rpath "${rpath}")
        endforeach()
        if(options)
            ffmpeg_command(ignored install_name_tool ${options} "${binary}")
        endif()
    endforeach()
    foreach(binary IN LISTS binaries)
        get_filename_component(name "${binary}" NAME)
        get_filename_component(directory "${binary}" DIRECTORY)
        ffmpeg_runtime_mac_dependencies("${binary}" dependencies)
        set(reached "")
        foreach(dependency IN LISTS dependencies)
            if(binary MATCHES "\\.dylib$" AND dependency STREQUAL "@rpath/${name}")
                continue()
            elseif(dependency MATCHES "^@loader_path/(.+)$")
                set(target "${directory}/${CMAKE_MATCH_1}")
                ffmpeg_inside("${target}" "${app}" contained)
                if(NOT contained OR NOT EXISTS "${target}" OR IS_DIRECTORY "${target}")
                    message(FATAL_ERROR "Broken relocated dependency in ${binary}: ${dependency}")
                endif()
                get_filename_component(dep_name "${target}" NAME)
                ffmpeg_family("${dep_name}" macos family)
                if(family)
                    list(APPEND reached "${family}")
                endif()
            elseif(NOT dependency MATCHES "^(/usr/lib/|/System/Library/)")
                message(FATAL_ERROR "Non-relocatable dependency in ${binary}: ${dependency}")
            endif()
        endforeach()
        ffmpeg_runtime_mac_rpaths("${binary}" rpaths)
        if(rpaths)
            message(FATAL_ERROR "Unexpected residual LC_RPATH in ${binary}: ${rpaths}")
        endif()
        if(binary STREQUAL main_binary)
            ffmpeg_runtime_require_families("${reached}" "${binary}")
        endif()
    endforeach()
    foreach(binary IN LISTS binaries)
        if(NOT binary STREQUAL main_binary)
            ffmpeg_command(ignored codesign --force --sign - --timestamp=none "${binary}")
        endif()
    endforeach()
    ffmpeg_command(ignored codesign --force --sign - --timestamp=none "${app}")
    ffmpeg_command(ignored codesign --verify --deep --strict "${app}")
endfunction()

function(ffmpeg_runtime_windows executable package_dir library_dir arch)
    get_filename_component(executable_dir "${executable}" DIRECTORY)
    if(NOT executable_dir STREQUAL library_dir)
        message(FATAL_ERROR "Windows release DLLs must be adjacent to OpenGromada.exe")
    endif()
    set(system_dlls
        advapi32 avicap32 avifil32 bcrypt cabinet cfgmgr32 comctl32 comdlg32 crypt32
        d3d11 d3d12 dbghelp dinput8 directmanipulation dnsapi dsound dwmapi dwrite dxgi dxva2
        gdi32 hid imm32 iphlpapi kernel32 mf mfplat mfreadwrite mfuuid mpr msacm32 msvcrt
        ncrypt netapi32 normaliz ntdll ole32 oleaut32 opengl32 powrprof propsys psapi
        rpcrt4 secur32 setupapi shell32 shcore shlwapi strmiids synchronization user32
        userenv usp10 ucrtbase uuid version vfw32 winhttp wininet winmm winspool wintrust ws2_32 wtsapi32)
    file(GLOB entries LIST_DIRECTORIES FALSE "${library_dir}/*")
    set(candidates "")
    foreach(path IN LISTS entries)
        get_filename_component(name "${path}" NAME)
        string(TOLOWER "${name}" name)
        if(name MATCHES "\\.dll$")
            string(SHA256 key "${name}")
            if(DEFINED local_${key})
                message(FATAL_ERROR "Ambiguous case-insensitive DLL name: ${name}")
            endif()
            set(local_${key} "${path}")
            list(APPEND candidates "${path}")
        endif()
    endforeach()
    ffmpeg_runtime_real_binaries("${executable}" "${candidates}" "${package_dir}" binaries)
    file(REAL_PATH "${executable}" main_binary)
    foreach(binary IN LISTS binaries)
        ffmpeg_check_architecture("${binary}" windows "${arch}")
        ffmpeg_command(output dumpbin /nologo /dependents "${binary}")
        ffmpeg_runtime_lines("${output}" lines)
        set(reached "")
        foreach(line IN LISTS lines)
            string(STRIP "${line}" name)
            string(TOLOWER "${name}" name)
            if(NOT name MATCHES "^[a-z0-9_.+-]+\\.dll$")
                continue()
            endif()
            string(SHA256 key "${name}")
            if(DEFINED local_${key})
                ffmpeg_family("${name}" windows family)
                if(family)
                    list(APPEND reached "${family}")
                endif()
            else()
                string(REGEX REPLACE "\\.dll$" "" stem "${name}")
                if(NOT name MATCHES "^(api-ms-win-|ext-ms-win-)" AND NOT stem IN_LIST system_dlls)
                    message(FATAL_ERROR "Unbundled non-system DLL in ${binary}: ${name}")
                endif()
            endif()
        endforeach()
        if(binary STREQUAL main_binary)
            ffmpeg_runtime_require_families("${reached}" "${binary}")
        endif()
    endforeach()
endfunction()

function(ffmpeg_fixup_runtime executable package_dir library_dir platform arch)
    foreach(path "${executable}" "${library_dir}")
        ffmpeg_inside("${path}" "${package_dir}" contained)
        if(NOT contained)
            message(FATAL_ERROR "Package runtime path escapes its staging directory: ${path}")
        endif()
    endforeach()
    if(platform STREQUAL "linux")
        ffmpeg_runtime_linux("${executable}" "${package_dir}" "${library_dir}" "${arch}")
    elseif(platform STREQUAL "macos")
        ffmpeg_runtime_macos("${executable}" "${package_dir}" "${library_dir}" "${arch}")
    elseif(platform STREQUAL "windows")
        ffmpeg_runtime_windows("${executable}" "${package_dir}" "${library_dir}" "${arch}")
    else()
        message(FATAL_ERROR "Unsupported package platform: ${platform}")
    endif()
endfunction()

function(ffmpeg_probe_runtime executable platform arch result)
    cmake_host_system_information(RESULT host_arch QUERY OS_PLATFORM)
    string(TOLOWER "${host_arch}" host_arch)
    if(platform STREQUAL "windows" AND arch STREQUAL "arm64" AND NOT host_arch MATCHES "^(arm64|aarch64)$")
        message(STATUS "Windows ARM64 cross-package: runtime probe skipped on non-ARM64 host; PE/import audit only")
        set("${result}" "skipped: Windows ARM64 cross-build on a non-ARM64 host" PARENT_SCOPE)
        return()
    endif()
    set(temp_parent "")
    foreach(candidate "$ENV{TMPDIR}" "$ENV{TEMP}" "$ENV{TMP}" /tmp)
        if(IS_ABSOLUTE "${candidate}" AND IS_DIRECTORY "${candidate}")
            file(REAL_PATH "${candidate}" temp_parent)
            break()
        endif()
    endforeach()
    if(NOT temp_parent)
        message(FATAL_ERROR "No absolute temporary directory is available for the isolated package probe")
    endif()
    set(probe_dir "")
    foreach(attempt RANGE 1 10)
        string(RANDOM LENGTH 32 ALPHABET 0123456789abcdef suffix)
        set(candidate "${temp_parent}/gromada-package-probe-${suffix}")
        if(NOT EXISTS "${candidate}" AND NOT IS_SYMLINK "${candidate}")
            set(probe_dir "${candidate}")
            break()
        endif()
    endforeach()
    if(NOT probe_dir)
        message(FATAL_ERROR "Cannot reserve a unique package probe directory")
    endif()
    file(MAKE_DIRECTORY "${probe_dir}/empty-data")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy
            "ALIEN_SHOOTER_PREF_PATH=${probe_dir}/prefs"
            "${executable}" --probe-game=json "--data-dir=${probe_dir}/empty-data" "--pref-path=${probe_dir}/prefs"
        WORKING_DIRECTORY "${probe_dir}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    file(REMOVE_RECURSE "${probe_dir}")
    if(EXISTS "${probe_dir}" OR IS_SYMLINK "${probe_dir}")
        message(FATAL_ERROR "Could not remove the isolated package probe directory: ${probe_dir}")
    endif()
    if(NOT status STREQUAL "1")
        message(FATAL_ERROR "Packaged probe must report missing data (exit 1), got ${status}:\n${output}${errors}")
    endif()
    string(JSON type ERROR_VARIABLE json_error TYPE "${output}" moviePlaybackAvailable)
    if(NOT json_error STREQUAL "NOTFOUND" OR NOT type STREQUAL "BOOLEAN")
        message(FATAL_ERROR "Packaged probe did not emit boolean moviePlaybackAvailable JSON:\n${output}${errors}")
    endif()
    string(JSON available GET "${output}" moviePlaybackAvailable)
    if(NOT available)
        message(FATAL_ERROR "Packaged executable reports movie playback unavailable:\n${output}${errors}")
    endif()
    message(STATUS "Packaged production --probe-game=json: moviePlaybackAvailable=true (asset-free isolated probe)")
    set("${result}" "passed: production --probe-game=json reports moviePlaybackAvailable=true" PARENT_SCOPE)
endfunction()
