cmake_minimum_required(VERSION 3.20)

if(NOT SHADERCROSS OR NOT EXISTS "${SHADERCROSS}")
    message(FATAL_ERROR "Set ALIEN_SHADERCROSS to the pinned shadercross executable; build it with cmake/BuildShaderTools.cmake")
endif()
if(NOT SOURCE_DIR OR NOT WORK_DIR)
    message(FATAL_ERROR "SOURCE_DIR and WORK_DIR are required")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
set(opcodes 0 1 100 101 102 103 104 200 201 300 301 302 303 304 305 306 307 308 309 310 311 500)
foreach(opcode IN LISTS opcodes)
    foreach(format SPIRV DXIL MSL)
        string(TOLOWER "${format}" name)
        execute_process(COMMAND "${SHADERCROSS}" shaders/legacy.hlsl -s HLSL -d "${format}"
            -t compute -e main -I shaders "-DGPU_OPCODE=${opcode}" --msl-version 2.1.0
            -o "${WORK_DIR}/${name}_${opcode}"
            WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Shader compilation failed for opcode ${opcode}, ${format}")
        endif()
    endforeach()
    file(READ "${WORK_DIR}/msl_${opcode}" metal)
    if(opcode EQUAL 0)
        set(bindings "Batch [[buffer(0)]]" "heap [[buffer(1)]]" "outputColor [[texture(0)]]")
    else()
        set(bindings "Batch [[buffer(0)]]" "commands [[buffer(1)]]" "tileIndices [[buffer(2)]]" "heap [[buffer(3)]]")
        string(FIND "${metal}" "outputColor" unexpected_output)
        if(NOT unexpected_output EQUAL -1)
            message(FATAL_ERROR "Unexpected output image in GPU opcode ${opcode}")
        endif()
    endif()
    foreach(binding IN LISTS bindings)
        string(FIND "${metal}" "${binding}" binding_position)
        if(binding_position EQUAL -1)
            message(FATAL_ERROR "Metal resource binding changed for GPU opcode ${opcode}: ${binding}")
        endif()
    endforeach()
    message(STATUS "Compiled GPU opcode ${opcode}")
endforeach()
set(header "#ifndef GPU_SHADERS_H\n#define GPU_SHADERS_H\n\n#include <cstddef>\n\nnamespace GPU_SHADERS {\n\n")
foreach(opcode IN LISTS opcodes)
    foreach(name spirv dxil msl)
        file(READ "${WORK_DIR}/${name}_${opcode}" bytes HEX)
        if(name STREQUAL "msl")
            string(APPEND bytes "00")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${bytes}")
        string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" bytes "${bytes}")
        string(APPEND header "alignas(16) inline constexpr unsigned char ${name}_${opcode}[] = {\n${bytes}\n};\n\n")
    endforeach()
endforeach()
string(APPEND header "struct Artifact {\n    unsigned opcode;\n    const unsigned char* spirv;\n    std::size_t spirvSize;\n    const unsigned char* dxil;\n    std::size_t dxilSize;\n    const unsigned char* msl;\n    std::size_t mslSize;\n};\n\ninline constexpr Artifact artifacts[] = {\n")
foreach(opcode IN LISTS opcodes)
    string(APPEND header "    {${opcode}, spirv_${opcode}, sizeof(spirv_${opcode}), dxil_${opcode}, sizeof(dxil_${opcode}), msl_${opcode}, sizeof(msl_${opcode})},\n")
endforeach()
string(APPEND header "};\n\n")
string(APPEND header "}\n\n#endif\n")
if(CHECK_ONLY)
    file(READ "${SOURCE_DIR}/src/gfx/gpu_shaders.h" existing)
    if(NOT header STREQUAL existing)
        message(FATAL_ERROR "Embedded shaders are stale; run regenerate-shaders using the pinned toolchain")
    endif()
else()
    file(WRITE "${SOURCE_DIR}/src/gfx/gpu_shaders.h.tmp" "${header}")
    file(RENAME "${SOURCE_DIR}/src/gfx/gpu_shaders.h.tmp" "${SOURCE_DIR}/src/gfx/gpu_shaders.h")
endif()
