cmake_minimum_required(VERSION 3.20)

function(ffmpeg_command output)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE stdout
        ERROR_VARIABLE stderr TIMEOUT 120)
    if(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "FFmpeg packaging command failed (${status}): ${ARGN}\n${stdout}${stderr}")
    endif()
    set(${output} "${stdout}" PARENT_SCOPE)
endfunction()

function(ffmpeg_resolve path output)
    set(candidate "${path}")
    if(CMAKE_HOST_WIN32)
        string(REPLACE "\\" "/" candidate "${candidate}")
    endif()
    cmake_path(ABSOLUTE_PATH candidate BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
    cmake_path(GET candidate ROOT_PATH resolved)
    cmake_path(GET candidate RELATIVE_PART relative)
    string(REPLACE "/" ";" components "${relative}")
    foreach(component IN LISTS components)
        if(component STREQUAL "" OR component STREQUAL ".")
            continue()
        elseif(component STREQUAL "..")
            get_filename_component(resolved "${resolved}" DIRECTORY)
        else()
            cmake_path(APPEND resolved "${component}")
        endif()
        if(EXISTS "${resolved}")
            file(REAL_PATH "${resolved}" resolved)
        elseif(IS_SYMLINK "${resolved}")
            set(${output} "" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(ffmpeg_inside path root output)
    ffmpeg_resolve("${path}" resolved)
    ffmpeg_resolve("${root}" resolved_root)
    if(resolved STREQUAL "" OR resolved_root STREQUAL "")
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    file(RELATIVE_PATH relative "${resolved_root}" "${resolved}")
    if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\.(/|$)")
        set(${output} FALSE PARENT_SCOPE)
    else()
        set(${output} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(ffmpeg_family name platform output)
    if(platform STREQUAL "windows")
        string(TOLOWER "${name}" name)
        set(pattern "^(avcodec|avformat|avutil|swresample|swscale)(-[0-9]+)?\\.dll$")
    elseif(platform STREQUAL "macos")
        set(pattern "^lib(avcodec|avformat|avutil|swresample|swscale)(\\.[0-9]+)*\\.dylib$")
    else()
        set(pattern "^lib(avcodec|avformat|avutil|swresample|swscale)\\.so(\\.[0-9]+)*$")
    endif()
    if(name MATCHES "${pattern}")
        set(${output} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${output} "" PARENT_SCOPE)
    endif()
endfunction()

function(ffmpeg_read path output)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Required FFmpeg source/build material is missing: ${path}")
    endif()
    file(READ "${path}" contents)
    set(${output} "${contents}" PARENT_SCOPE)
endfunction()

function(ffmpeg_json_string value output)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(ffmpeg_json_set document key value)
    ffmpeg_json_string("${value}" encoded)
    string(JSON result SET "${${document}}" "${key}" "${encoded}")
    set(${document} "${result}" PARENT_SCOPE)
endfunction()

function(ffmpeg_copy_source source destination)
    if(IS_SYMLINK "${source}")
        message(FATAL_ERROR "Source copy root must not be a symlink: ${source}")
    endif()
    if(CMAKE_HOST_UNIX)
        ffmpeg_command(special find "${source}" ! -type f ! -type d ! -type l -print)
        if(NOT special STREQUAL "")
            message(FATAL_ERROR "Special file in corresponding source: ${special}")
        endif()
    endif()
    set(entries "${source}")
    if(IS_DIRECTORY "${source}")
        file(GLOB_RECURSE children LIST_DIRECTORIES TRUE "${source}/*")
        list(APPEND entries ${children})
    endif()
    foreach(entry IN LISTS entries)
        if(IS_SYMLINK "${entry}")
            file(READ_SYMLINK "${entry}" target)
            if(IS_ABSOLUTE "${target}" OR target MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
                message(FATAL_ERROR "Escaping source symlink: ${entry} -> ${target}")
            endif()
        endif()
    endforeach()
    get_filename_component(parent "${destination}" DIRECTORY)
    get_filename_component(name "${source}" NAME)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY "${source}" DESTINATION "${parent}" USE_SOURCE_PERMISSIONS)
    if(NOT "${parent}/${name}" STREQUAL "${destination}")
        file(RENAME "${parent}/${name}" "${destination}")
    endif()
endfunction()

foreach(variable IN ITEMS FFMPEG_VCPKG_ROOT FFMPEG_TRIPLET FFMPEG_PACKAGE_DIR FFMPEG_SOURCE_DIR)
    if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
        message(FATAL_ERROR "Specify -D${variable}=... before -P cmake/PackageFFmpeg.cmake")
    endif()
endforeach()
if(NOT FFMPEG_TRIPLET MATCHES "^(x86|x64|arm64)-[A-Za-z0-9_-]+$")
    message(FATAL_ERROR "Invalid or unsupported FFmpeg triplet: ${FFMPEG_TRIPLET}")
endif()
set(arch "${CMAKE_MATCH_1}")
if(NOT DEFINED FFMPEG_PLATFORM)
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(FFMPEG_PLATFORM linux)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
        set(FFMPEG_PLATFORM macos)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        set(FFMPEG_PLATFORM windows)
    endif()
endif()
if(NOT FFMPEG_PLATFORM MATCHES "^(linux|macos|windows)$")
    message(FATAL_ERROR "Unsupported packaging host: ${CMAKE_HOST_SYSTEM_NAME}")
endif()
foreach(variable IN ITEMS FFMPEG_VCPKG_ROOT FFMPEG_PACKAGE_DIR FFMPEG_SOURCE_DIR)
    if(NOT IS_DIRECTORY "${${variable}}")
        message(FATAL_ERROR "Required directory does not exist: ${${variable}}")
    endif()
    ffmpeg_resolve("${${variable}}" ${variable})
endforeach()
set(vcpkg "${FFMPEG_VCPKG_ROOT}")
set(package "${FFMPEG_PACKAGE_DIR}")
set(project "${FFMPEG_SOURCE_DIR}")
ffmpeg_inside("${vcpkg}" "${package}" vcpkg_in_package)
ffmpeg_inside("${project}" "${package}" project_in_package)
ffmpeg_inside("${package}" "${vcpkg}" package_in_vcpkg)
if(vcpkg_in_package OR project_in_package OR package_in_vcpkg)
    message(FATAL_ERROR "Use a separate installed release staging directory outside vcpkg; it must not contain the project or vcpkg")
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" -E environment OUTPUT_VARIABLE environment
    RESULT_VARIABLE status)
if(NOT "${status}" STREQUAL "0")
    message(FATAL_ERROR "Cannot inspect the packaging environment")
endif()
string(REPLACE "\n" ";" environment "${environment}")
foreach(entry IN LISTS environment)
    if(entry MATCHES "^((LD_|DYLD_)[^=]*)=")
        unset(ENV{${CMAKE_MATCH_1}})
    endif()
endforeach()
set(ENV{LC_ALL} C)
set(ENV{VSLANG} 1033)
include("${CMAKE_CURRENT_LIST_DIR}/FFmpegRuntime.cmake")

set(prefix "${vcpkg}/installed/${FFMPEG_TRIPLET}")
if(FFMPEG_PLATFORM STREQUAL "macos")
    file(GLOB apps "${package}/*.app")
    list(LENGTH apps app_count)
    if(NOT app_count EQUAL 1)
        message(FATAL_ERROR "Expected exactly one installed .app in ${package}")
    endif()
    list(GET apps 0 app)
    set(executable "${app}/Contents/MacOS/OpenGromada")
    set(library_dir "${app}/Contents/Frameworks")
    set(notice_dir "${app}/Contents/Resources/third-party/ffmpeg")
else()
    set(executable "${package}/OpenGromada")
    if(FFMPEG_PLATFORM STREQUAL "windows")
        string(APPEND executable ".exe")
    endif()
    set(library_dir "${package}")
    set(notice_dir "${package}/third-party/ffmpeg")
endif()
if(NOT EXISTS "${executable}" OR IS_DIRECTORY "${executable}" OR IS_SYMLINK "${executable}")
    message(FATAL_ERROR "Installed executable is missing or not a regular file: ${executable}")
endif()
foreach(output IN ITEMS "${executable}" "${library_dir}" "${notice_dir}" "${package}/FFmpeg-package.json")
    ffmpeg_inside("${output}" "${package}" contained)
    if(NOT contained)
        message(FATAL_ERROR "Package output escapes the release staging tree: ${output}")
    endif()
endforeach()
if(EXISTS "${notice_dir}" OR EXISTS "${package}/FFmpeg-package.json")
    message(FATAL_ERROR "FFmpeg notices/manifest already exist; use a fresh install staging tree")
endif()
ffmpeg_check_architecture("${executable}" "${FFMPEG_PLATFORM}" "${arch}")

set(shared_dir "${prefix}/lib")
if(FFMPEG_PLATFORM STREQUAL "windows")
    set(shared_dir "${prefix}/bin")
endif()
file(GLOB entries "${shared_dir}/*")
set(libraries "")
foreach(entry IN LISTS entries)
    get_filename_component(name "${entry}" NAME)
    ffmpeg_family("${name}" "${FFMPEG_PLATFORM}" family)
    if(family)
        ffmpeg_inside("${entry}" "${shared_dir}" contained)
        if(NOT EXISTS "${entry}" OR IS_DIRECTORY "${entry}" OR NOT contained)
            message(FATAL_ERROR "Broken or escaping shared FFmpeg library: ${entry}")
        endif()
        file(REAL_PATH "${entry}" real)
        list(APPEND family_${family} "${real}")
        if(IS_SYMLINK "${entry}")
            file(READ_SYMLINK "${entry}" target)
            get_filename_component(target "${target}" ABSOLUTE BASE_DIR "${shared_dir}")
            get_filename_component(target_parent "${target}" DIRECTORY)
            get_filename_component(target_name "${target}" NAME)
            ffmpeg_family("${target_name}" "${FFMPEG_PLATFORM}" target_family)
            if(NOT target_parent STREQUAL shared_dir OR NOT target_family STREQUAL family)
                message(FATAL_ERROR "Unsupported library symlink chain: ${entry}")
            endif()
        endif()
        if(EXISTS "${library_dir}/${name}" OR IS_SYMLINK "${library_dir}/${name}")
            message(FATAL_ERROR "Refusing to overwrite an existing package library: ${library_dir}/${name}")
        endif()
        list(APPEND libraries "${entry}")
    endif()
endforeach()
foreach(family IN ITEMS avcodec avformat avutil swresample swscale)
    list(REMOVE_DUPLICATES family_${family})
    list(LENGTH family_${family} count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one shared ${family} version in ${shared_dir}; found ${count}")
    endif()
endforeach()

set(port "${vcpkg}/ports/ffmpeg")
set(tree "${vcpkg}/buildtrees/ffmpeg")
set(build "${tree}/${FFMPEG_TRIPLET}-rel")
ffmpeg_read("${port}/vcpkg.json" port_manifest)
string(JSON version ERROR_VARIABLE json_error GET "${port_manifest}" version)
if(json_error)
    string(JSON version ERROR_VARIABLE json_error GET "${port_manifest}" version-semver)
endif()
if(json_error OR NOT version MATCHES "^[0-9]+(\\.[0-9]+)+$")
    message(FATAL_ERROR "Missing FFmpeg version in port manifest")
endif()
ffmpeg_read("${build}/build.sh" build_script)
string(REGEX MATCH "(^|\n)PATH_TO_SRC_DIR=\"([^\"\r\n]+)\"[ \t\r]*(\n|$)" assignment "${build_script}")
if(NOT assignment)
    message(FATAL_ERROR "Cannot identify exact patched FFmpeg source from build.sh")
endif()
set(patched "${CMAKE_MATCH_2}")
if(CMAKE_HOST_WIN32 AND patched MATCHES "^/([a-zA-Z])/(.*)$")
    set(patched "${CMAKE_MATCH_1}:/${CMAKE_MATCH_2}")
endif()
ffmpeg_inside("${patched}" "${tree}/src" contained)
if(NOT IS_ABSOLUTE "${patched}" OR NOT IS_DIRECTORY "${patched}" OR NOT contained)
    message(FATAL_ERROR "Missing or unexpected patched FFmpeg source: ${patched}")
endif()
ffmpeg_resolve("${patched}" patched)
foreach(required IN ITEMS configure LICENSE.md COPYING.LGPLv2.1 libavcodec libavformat)
    if(NOT EXISTS "${patched}/${required}")
        message(FATAL_ERROR "Incomplete corresponding source: ${patched}/${required}")
    endif()
endforeach()
ffmpeg_read("${build}/config.h" config)
string(REPLACE "\r\n" "\n" config_lines "${config}")
string(REPLACE "\n" ";" config_lines "${config_lines}")
foreach(feature IN ITEMS GPL NONFREE VERSION3 SHARED)
    set(enabled 0)
    if(feature STREQUAL "SHARED")
        set(enabled 1)
    endif()
    set(declarations 0)
    foreach(line IN LISTS config_lines)
        if(line MATCHES "^[ \t]*#[ \t]*(define|undef)[ \t]+CONFIG_${feature}([ \t]|$)")
            math(EXPR declarations "${declarations} + 1")
            if(NOT line MATCHES "^[ \t]*#[ \t]*define[ \t]+CONFIG_${feature}[ \t]+${enabled}[ \t]*$")
                message(FATAL_ERROR "Refusing non-LGPL-2.1 shared configuration: CONFIG_${feature}")
            endif()
        endif()
    endforeach()
    if(NOT declarations EQUAL 1)
        message(FATAL_ERROR "Refusing non-LGPL-2.1 shared configuration: CONFIG_${feature}")
    endif()
endforeach()
ffmpeg_read("${build}/ffbuild/config.mak" unused)
set(copyright "${prefix}/share/ffmpeg/copyright")
ffmpeg_read("${copyright}" copyright_text)
if(NOT copyright_text MATCHES "GNU LESSER GENERAL PUBLIC LICENSE")
    message(FATAL_ERROR "Missing LGPL text in installed FFmpeg copyright notice")
endif()
ffmpeg_read("${project}/docs/FFmpeg.md" unused)
set(build_log "${tree}/build-${FFMPEG_TRIPLET}-rel-out.log")
ffmpeg_read("${build_log}" build_output)
if(NOT build_output MATCHES "License: LGPL version 2\\.1 or later")
    message(FATAL_ERROR "FFmpeg build output does not confirm LGPL version 2.1 or later")
endif()
ffmpeg_command(commit git -C "${vcpkg}" rev-parse HEAD)
string(STRIP "${commit}" commit)
string(LENGTH "${commit}" commit_length)
if(NOT commit_length EQUAL 40 OR NOT commit MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Cannot identify pinned vcpkg revision")
endif()

set(recipe_sources "${build_log}")
set(recipe_targets "recipe/build-output.log")
foreach(name IN ITEMS ffmpeg ffmpeg-bin2c vcpkg-cmake-get-vars vcpkg-pkgconfig-get-modules)
    if(NOT IS_DIRECTORY "${vcpkg}/ports/${name}")
        message(FATAL_ERROR "Missing pinned vcpkg build helper recipe: ${name}")
    endif()
    list(APPEND recipe_sources "${vcpkg}/ports/${name}")
    list(APPEND recipe_targets "recipe/ports/${name}")
endforeach()
foreach(name IN ITEMS build.sh config.h config_components.h cflags.rsp ldflags.rsp ffbuild/config.mak ffbuild/config.log)
    if(EXISTS "${build}/${name}")
        list(APPEND recipe_sources "${build}/${name}")
        list(APPEND recipe_targets "recipe/generated/${name}")
    endif()
endforeach()
set(matching_triplet FALSE)
foreach(directory IN ITEMS .github/triplets cmake/triplets triplets)
    file(GLOB_RECURSE triplets "${project}/${directory}/*.cmake")
    foreach(path IN LISTS triplets)
        file(RELATIVE_PATH relative "${project}" "${path}")
        list(APPEND recipe_sources "${path}")
        list(APPEND recipe_targets "recipe/project/${relative}")
        get_filename_component(name "${path}" NAME)
        if(name STREQUAL "${FFMPEG_TRIPLET}.cmake")
            set(matching_triplet TRUE)
        endif()
    endforeach()
endforeach()
if(NOT matching_triplet)
    foreach(directory IN ITEMS triplets triplets/community)
        set(path "${vcpkg}/${directory}/${FFMPEG_TRIPLET}.cmake")
        if(EXISTS "${path}")
            list(APPEND recipe_sources "${path}")
            list(APPEND recipe_targets "recipe/vcpkg/${directory}/${FFMPEG_TRIPLET}.cmake")
            set(matching_triplet TRUE)
        endif()
    endforeach()
endif()
if(NOT matching_triplet)
    message(FATAL_ERROR "Source for selected vcpkg triplet is missing: ${FFMPEG_TRIPLET}")
endif()
foreach(name IN ITEMS vcpkg.json vcpkg-configuration.json CMakeLists.txt .github/workflows/portable.yml
        .github/actions/setup-movies/action.yml cmake/PackageFFmpeg.cmake cmake/FFmpegRuntime.cmake)
    if(EXISTS "${project}/${name}")
        list(APPEND recipe_sources "${project}/${name}")
        list(APPEND recipe_targets "recipe/project/${name}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${library_dir}" "${notice_dir}")
set(bundled "")
foreach(source IN LISTS libraries)
    get_filename_component(name "${source}" NAME)
    if(IS_SYMLINK "${source}")
        file(READ_SYMLINK "${source}" target)
        get_filename_component(target "${target}" NAME)
        file(CREATE_LINK "${target}" "${library_dir}/${name}" SYMBOLIC)
    else()
        file(COPY "${source}" DESTINATION "${library_dir}" USE_SOURCE_PERMISSIONS)
        file(CHMOD "${library_dir}/${name}" PERMISSIONS
            OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
        list(APPEND bundled "${library_dir}/${name}")
    endif()
endforeach()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(stage "${notice_dir}/ffmpeg-source-${nonce}")
if(EXISTS "${stage}" OR IS_SYMLINK "${stage}")
    message(FATAL_ERROR "Temporary source staging path already exists: ${stage}")
endif()
file(MAKE_DIRECTORY "${stage}")
ffmpeg_copy_source("${patched}" "${stage}/ffmpeg-${version}")
list(LENGTH recipe_sources recipe_count)
math(EXPR last_recipe "${recipe_count} - 1")
foreach(index RANGE 0 ${last_recipe})
    list(GET recipe_sources ${index} source)
    list(GET recipe_targets ${index} target)
    ffmpeg_copy_source("${source}" "${stage}/${target}")
endforeach()
set(metadata "{}")
ffmpeg_json_set(metadata ffmpeg_version "${version}")
ffmpeg_json_set(metadata vcpkg_commit "${commit}")
ffmpeg_json_set(metadata triplet "${FFMPEG_TRIPLET}")
ffmpeg_json_set(metadata source "Exact patched source consumed by the generated build.sh")
ffmpeg_json_set(metadata rebuild "Use the enclosed project recipes/triplets and pinned vcpkg commit; generated build.sh records the original configure command and paths.")
file(WRITE "${stage}/BUILD.json" "${metadata}\n")
set(source_archive "${notice_dir}/corresponding-source.tar.gz")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${stage}/source.tar.gz"
    --format=gnutar -- "ffmpeg-${version}" recipe BUILD.json
    WORKING_DIRECTORY "${stage}" RESULT_VARIABLE status ERROR_VARIABLE stderr)
if(NOT "${status}" STREQUAL "0")
    message(FATAL_ERROR "Cannot archive FFmpeg corresponding source: ${status}\n${stderr}")
endif()
file(RENAME "${stage}/source.tar.gz" "${source_archive}")
file(REMOVE_RECURSE "${stage}")
file(COPY "${copyright}" "${patched}/COPYING.LGPLv2.1" "${project}/docs/FFmpeg.md"
    DESTINATION "${notice_dir}" USE_SOURCE_PERMISSIONS)

ffmpeg_fixup_runtime("${executable}" "${package}" "${library_dir}" "${FFMPEG_PLATFORM}" "${arch}")
ffmpeg_probe_runtime("${executable}" "${FFMPEG_PLATFORM}" "${arch}" runtime_probe)
set(manifest "{}")
ffmpeg_json_set(manifest ffmpeg_version "${version}")
ffmpeg_json_set(manifest triplet "${FFMPEG_TRIPLET}")
ffmpeg_json_set(manifest platform "${FFMPEG_PLATFORM}")
ffmpeg_json_set(manifest architecture "${arch}")
set(hashes "{}")
foreach(path IN LISTS bundled)
    file(RELATIVE_PATH relative "${package}" "${path}")
    file(SHA256 "${path}" hash)
    ffmpeg_json_set(hashes "${relative}" "${hash}")
endforeach()
string(JSON manifest SET "${manifest}" shared_libraries "${hashes}")
file(RELATIVE_PATH relative "${package}" "${source_archive}")
file(SHA256 "${source_archive}" hash)
set(hashes "{}")
ffmpeg_json_set(hashes "${relative}" "${hash}")
string(JSON manifest SET "${manifest}" corresponding_source "${hashes}")
ffmpeg_json_set(manifest verification "Shared-library architecture and relocated dependency closure; actual media playback is verified separately.")
ffmpeg_json_set(manifest runtime_probe "${runtime_probe}")
file(WRITE "${package}/FFmpeg-package.json" "${manifest}\n")
message(STATUS "Packaged FFmpeg ${version}: five shared libraries, corresponding source, ${FFMPEG_PLATFORM}/${arch} dependency audit passed")
